In [22]:
from torch.utils.data import DataLoader,Dataset
from torchvision.transforms import ToTensor
import ipywidgets as widgets
import time
import matplotlib.pyplot as plt
import matplotlib as mpl
import os
import pandas as pd
import numpy as np

# from torchvision.io import read_image
import torch
import torch.nn as nn

from IPython.display import Javascript

def alert_when_done():
    alert = Javascript("alert('Done')")
    display(alert)

In [81]:
device="mps"
class CtoF_RandomDataset(Dataset):
    def c_to_f(self, c):
        return np.float32((c*9/5) + 32)

    def __init__(self, low, high, size, precision=3, device="cpu"):
        self.data = pd.DataFrame(columns=("features", "labels"), dtype="float32")
        self.data["features"] = np.round(np.random.uniform(low, high, size), precision)
        self.data["labels"] = self.data["features"].apply(self.c_to_f)
        
        self.features = torch.tensor(np.c_[np.float32(self.data["features"].values)], device=device)
        self.labels = torch.tensor(np.c_[np.float32(self.data["labels"].values)], device=device)
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        # feature, label = self.data.iloc[idx].values
        # feature = torch.tensor(feature, device=device)
        # label = torch.tensor(label, device=device)
        # return np.float32(feature), np.float32(label)
        # return np.float32(feature), np.float32(label)
        return self.features[idx], self.labels[idx]
        
dataset = CtoF_RandomDataset(0, 300, 160*1000, device=device)
dataloader = DataLoader(dataset, batch_size=100)

In [82]:
class LinearRegression(nn.Module):
    def __init__(self):
        super(LinearRegression, self).__init__()
        self.linear_stack = nn.Sequential(
        nn.Linear(1,1)
        )
    
    def forward(self, x):
        return self.linear_stack(x)
    
model = LinearRegression().to(device)


In [83]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[0.4398]], device='mps:0', requires_grad=True)
Parameter containing:
tensor([-0.1815], device='mps:0', requires_grad=True)


In [84]:
learning_rate = 1e-1

In [85]:
from IPython.display import clear_output
# pred = model(torch.tensor([feature], device=device))
# loss = loss_fn(pred, torch.tensor([label], device=device))

def train_loop(dataloader, model, loss_fn, optimizer, device="mps"):
    # out = widgets.Output(layout={"border":"2px solid black", "min-height":"400px"})
    # display(out)
    # losses = np.array([])
    # bigPreds = np.array([])
    # fig, ax = plt.subplots()
    for batch, (features, labels) in enumerate(dataloader):
        
        preds = model(features)
        loss = loss_fn(preds, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # if batch == 15:
            # print(f"{preds}-p-\n, {labels}-l-\n, {loss}")
        
        print(f"loss: {loss} --- batch: {batch+1}/{int(len(dataloader.dataset)/dataloader.batch_size)}".ljust(100),
              end="\r")
        # with out:
        #     ax.clear()
        #     clear_output(wait=True)
        #     ax.scatter(features, preds.to("cpu").detach().numpy())
        #     ax.plot(features, [(i*9/5)+32 for i in features])
        #     display(ax.figure)
        
    # plt.close(fig)
        # bigPreds = np.append(bigPreds,preds.to("cpu").detach().numpy())
        
    # display(losses)
    # ax.scatter(dataset.data["features"].values, bigPreds)
    # display(ax.figure)
    print("\n")
    return loss
        
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [86]:
epochs = 200
plt.ioff()
start_time = time.localtime(time.time())
print("Start Time: " + time.strftime("%H:%M:%S", start_time))
losses = np.zeros((epochs))
for i in range(epochs):
    print(f"Epoch {i+1} -----------", end="\n")
    losses[i] = train_loop(dataloader, model, loss_fn, optimizer, device).item()
    
    
end_time = time.localtime(time.time())
print("Start Time: " + time.strftime("%H:%M:%S", start_time), end="---")
print("End Time: " + time.strftime("%H:%M:%S", end_time))
print(f"Duration = {time.mktime(end_time) - time.mktime(start_time)} seconds")

_,ax = plt.subplots()
# ax.clear()
# ax.plot(losses)
# display(ax.figure)
alert_when_done()

Start Time: 23:40:14
Epoch 1 -----------
loss: 2.9106929302215576 --- batch: 1600/1600                                                       

Epoch 2 -----------


KeyboardInterrupt: 

In [ ]:
#cpu = 77


In [71]:
x,y = next(iter(dataloader))

In [72]:
x

tensor([[1.2970e+02],
        [5.3820e+00],
        [1.7454e+02],
        [1.7771e+02],
        [1.1941e+02],
        [2.4487e+02],
        [1.6967e+01],
        [1.1979e+02],
        [7.0706e+01],
        [2.2612e+01],
        [2.3490e+00],
        [2.0933e+02],
        [2.6756e+01],
        [1.6297e+02],
        [7.4512e+01],
        [8.0277e+01],
        [1.3568e+02],
        [6.9985e+01],
        [2.3864e+02],
        [2.4133e+02],
        [2.8857e+02],
        [1.0408e+02],
        [2.6132e+02],
        [2.8342e+02],
        [2.6008e+02],
        [1.3461e+02],
        [1.6762e+02],
        [2.3228e+02],
        [2.5539e+02],
        [1.1597e+02],
        [1.8513e+02],
        [2.9378e+02],
        [9.3099e+01],
        [1.0010e+02],
        [1.7641e+02],
        [7.2430e+00],
        [2.6066e+02],
        [2.5868e+02],
        [2.2963e+02],
        [1.2212e+02],
        [4.0936e+01],
        [1.4283e+01],
        [1.2163e+02],
        [1.9115e+02],
        [2.8019e+02],
        [7

In [20]:
y

tensor([[566.4092],
        [363.3530],
        [301.2548],
        [387.0248],
        [115.6424]], device='mps:0')

In [157]:
np.append(points.get_offsets().data,np.c_[x,y], axis=0)

array([[249.742     , 481.53561401],
       [ 43.414     , 110.14520264],
       [146.103     , 294.9854126 ],
       [ 24.678     ,  76.42040253],
       [269.47      , 517.04602051],
       [256.809     , 494.25619507],
       [ 63.383     , 146.08940125],
       [112.254     , 234.0572052 ],
       [235.798     , 456.43640137],
       [226.751     , 440.15179443],
       [ 18.587     ,  65.45659637]])

In [17]:
torch.tensor(np.c_[np.float32(dataset.data["features"].values)], device="mps")

tensor([[222.1720],
        [149.5060],
        [ 38.2350],
        ...,
        [ 63.3310],
        [230.3010],
        [145.2810]], device='mps:0')